### ISSUE TITLE
Thoughts on incorporating `rust-problem-matchers` into `rust-check.yaml`?

### ISSUE THREAD

**Issue by DrewMcArthur** [ectobit/reusable-workflows#59]
Found this recently, and it works great.  Since I found your blog post, and like your reusable workflow, thought I'd bring this to your attention!

https://github.com/r7kamura/rust-problem-matchers

This allows build errors to show up directly on the diffs section of a pull request.  See them in action [here](https://github.com/DrewMcArthur/rsky/pull/5/files#diff-757b43130772208b58e8f76df8e9bd519873885497095e7d3dec5fae70f730baL547).

**Comment by acim** [comment]
Unfortunately I do not develop in Rust so I don’t need it, but if you would like to improve Rust support in this project, please be free to contribute. Thank you in advance.
